//go:build !byollvm && linux && !llvm12 && !llvm11
// +build !byollvm,linux,!llvm12,!llvm11

package llvm

// Automatically generated by `make config BUILDDIR=`, do not edit.

// #cgo CPPFLAGS: -I/usr/lib/llvm-13/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
// #cgo CXXFLAGS: -std=c++14
// #cgo LDFLAGS: -L/usr/lib/llvm-13/lib  -lLLVM-13
import "C"

type run_build_sh int
