// +build !byollvm

package llvm

// Automatically generated by `make config BUILDDIR=`, do not edit.

// #cgo CPPFLAGS: -I"C:/Program Files/LLVM/include"   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
// #cgo CXXFLAGS: -std=c++11
// #cgo LDFLAGS: -L"C:/Program Files/LLVM/lib" -lLLVM
import "C"

type (run_build_sh int)
